models/Project.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "project".
 *
 * @property integer $id
 * @property string $title
 * @property string $pm
 * @property string $command
 *
 * @property ProjectObject[] $projectObjects
 * @property Report[] $reports
 */
class Project extends ActiveRecord
{
    /**
     * @inheritdoc
     */    
    public static function tableName()
    {
        return 'project';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'pm', 'command'], 'required'],
            [['title', 'pm'], 'string', 'max' => 255],
            [['command'], 'safe'],           
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название проекта',
            'pm' => 'Руководитель проекта',
            'command' => 'Группа проекта',
        ];
    }

    public function afterFind()
    {
        parent::afterFind();

        $this->command = explode(', ', $this->command);
    }

    public function beforeSave($insert)
    {
        $this->command = implode(', ', $this->command);
        return parent::beforeSave($insert);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjectObjects()
    {
        return $this->hasMany(ProjectObject::className(), ['project_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReports()
    {
        return $this->hasMany(Report::className(), ['project_id' => 'id']);
    }

    public function getUsers()
    {
        return $this->hasMany(Users::className(), ['id' => 'pm']);
    }

    public function beforeDelete()
    {
        $constraits = ProjectObject::findAll(['project_id' => $this->id]);

        foreach ($constraits as $item)
        {
            $item->delete();
        }

        Report::updateAll(['project_id' => null], ['project_id' => $this->id]);

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}

controllers/ProjectController.php
<?php

namespace app\controllers;

use app\models\ProjectObject;
use app\models\User;
use Yii;
use app\models\Project;
use app\models\ProjectSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\models\Uploads;
use app\models\Work;
use app\models\Object;
use app\models\Section;
use app\models\Workcount;

/**
 * ProjectController implements the CRUD actions for Project model.
 */
class ProjectController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Project models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Project model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionUpload($id)
    {
       $model = new Uploads();
       $model->proyekt_id = $id;
        if (Yii::$app->request->isPost && $model->load(Yii::$app->request->post() )) {
            $model->File = UploadedFile::getInstance($model, 'File');
            
            if ($model->upload()) {
                return $this->redirect(['getexcel', 'id' => $model->proyekt_id]);            
            }
        }

       //$model->proyekt_id = $id;
       return $this->render('form', ['model' => $model]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Project();
        $button = 0;
        //if(isset($_POST['button1']))echo "birinchisi";
        if(isset($_POST['button2']))$button = 1;

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            $alreadySelected = ProjectObject::findAll(['project_id' => $model->id]);

            $selected = [];

            foreach ($alreadySelected as $items)
            {
                $selected[] = $items->object->id;
            }

            foreach ($alreadySelected as $item)
            {
                $item->delete();
            }

            $post = Yii::$app->request->post('ProjectObject');

            if (is_array($post['object_id']))
            {
                $post = $post['object_id'];

                foreach ($post as $key => $item)
                {
                    $projectObject = new ProjectObject();
                    $projectObject->project_id = $model->id;
                    $projectObject->object_id = $item;
                    $projectObject->save();
                }
            }
            if($button == 1) return $this->redirect(['upload','id'=>$model->id]);
            else return $this->redirect(['update','id'=>$model->id]);
        }
        else
        {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            $alreadySelected = ProjectObject::findAll(['project_id' => $model->id]);

            $selected = [];

            foreach ($alreadySelected as $items)
            {
                $selected[] = $items->object->id;
            }

            foreach ($alreadySelected as $item)
            {
                $item->delete();
            }

            $post = Yii::$app->request->post('ProjectObject');
/*echo "<pre>";
print_r(Yii::$app->request->post());
die;*/
            if (is_array($post['object_id']))
            {
                $post = $post['object_id'];

                foreach ($post as $key => $item)
                {
                    $projectObject = new ProjectObject();
                    $projectObject->project_id = $model->id;
                    $projectObject->object_id = $item;
                    $projectObject->save();
                }
            }
            return $this->redirect(['update','id'=>$model->id]);
        }
        else
        {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function GetExcelValues()
    {
        $inputFile = 'upload/excelfileimport.xlsx';        
        try{
            $inputFileType = \PHPExcel_IOFactory::identify($inputFile);
            $objReader = \PHPExcel_IOFactory::createReader($inputFileType);
            $objPHPExcel = $objReader->load($inputFile);
        }
        catch(Exception $e)  {  die('Error');  }

        $sheet = $objPHPExcel->getSheet(0);
        $highestRow = $sheet->getHighestRow();
        $highestColumn = $sheet->getHighestColumn();

        $data = []; $error = '<b style="color: #ff0000;"> <i>Нет сведения </i></b>';$validatsiya = 1;
        
        for($row = 2; $row <= $highestRow; $row++)
        {
            $rowData = $sheet->rangeToArray('A'.$row.':'.$highestColumn.$row,NULL,TRUE,FALSE);
           /* echo "w=".$rowData[0][0];
              echo "<pre>";
              print_r($rowData);
              echo "</pre>";
              die;*/
                                                
            if($row == 1)   {continue; }
            if($rowData[0][0]==""|$rowData[0][1]==""|$rowData[0][2] ==""|$rowData[0][3]==""|$rowData[0][4]==""|$rowData[0][5]=="")$validatsiya = 0;
            $data [] = [
                'proyekt' => $rowData[0][0] == "" ? $error : $rowData[0][0],
                'obyekt' => $rowData[0][1] == "" ? $error : $rowData[0][1],
                'razdel' => $rowData[0][2] == "" ? $error : $rowData[0][2],
                'name' => $rowData[0][3] == "" ? $error : $rowData[0][3],
                'izmereniya' => $rowData[0][4] == "" ? $error : $rowData[0][4],
                'count' => $rowData[0][5] == "" ? $error : $rowData[0][5],
            ]; 
        }
        $result [] = [
            'data' => $data,
            'validatsiya' => $validatsiya, 
        ];
        return $result;
    }
    public function Write_to_db($data,$id)
    {  /* echo "id=".$id;
        echo "<pre>";
        print_r($data);
        echo "</pre>";
        die;*/
        foreach ($data as $value) {
            //echo "f=".$value['obyekt'];die;
            $object = Object::find()->where([ 'title' => $value['obyekt'] ])->one();
            if(isset($object)){ $object_id = $object->id; }
            else {
                $model = new Object();
                $model->title = $value['obyekt'];
                $model->save();
                $object_id = $model->id;
            }

            $project_object = ProjectObject::find()->where(['project_id' => $id, 'object_id' => $object_id])->one();
            if(!isset($project_object)){ 
                $model = new ProjectObject();
                $model->project_id = $id;
                $model->object_id = $object_id;
                $model->save();
            }

            $section = Section::find()->where(['title' => $value['razdel'], 'object_id' => $object_id])->one();
            if(!isset($section)){ 
                $model = new Section();
                $model->title = $value['razdel'];
                $model->object_id = $object_id;
                $model->save();
                $section_id = $model->id;
            }
            else { $section_id = $section->id; }

            $work = Work::find()->where(['title' => $value['name'], 'unit' => $value['izmereniya']])->one();
            if(!isset($work)){ 
                $model = new Work();
                $model->title = $value['name'];
                $model->unit = $value['izmereniya'];
                $model->save();
                $work_id = $model->id;
            }
            else { $work_id = $work->id; }

            $work_count = new Workcount();
            $work_count->project_id = $id;
            $work_count->object_id = $object_id;
            $work_count->section = $section_id;
            $work_count->work_id = $work_id;
            $work_count->units = $value['izmereniya'];
            $work_count->count = $value['count'];
            $work_count->count_fact = 0.0;
            $work_count->save();
            /*if( $work_count->save() )echo "saqlandi";
            else echo "not";
           
              */
             /*echo "<pre>";
            print_r( $work_count->errors);
            echo "</pre>";
            die; */
            /*echo "<pre>";
        print_r($work_count);
        echo "</pre>";
        die;*/
        }
    }

    public function SortingValues($data,$id)
    {
        $allworks = \app\models\Workcount::find()->where(['project_id' => $id])->all();

        $works = [];
        foreach ($allworks as $value) {
           $works [] =[
                'proyekt' => Project::find()->where(['id' => $value['project_id']])->one()->title,

views/project/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $form yii\widgets\ActiveForm */

$works = new \app\models\ObjectSection();

$alreadySelected = \app\models\ProjectObject::findAll(['project_id' => $model->id]);
$selected = [];
$users = \app\models\Users::find()->all();
foreach ($alreadySelected as $items)
{
    $selected[] = $items->object->id;
}

$data = \app\models\Object::find()->all();
$result = [];
foreach ($data as $item)
{
    $result[$item->id] = $item->title;
}

\yii\helpers\Url::remember();
?>

<div class="project-form">
    <div class="box box-default">
        <div class="box-body">
            <?php $form = ActiveForm::begin(); ?>

            <div class="row">
                <div class="col-md-3 vcenter">
                    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-md-3 vcenter">
                    <?= $form->field($model, 'pm')->widget(\kartik\select2\Select2::classname(), [
                        'data' => \yii\helpers\ArrayHelper::map($users, 'id', 'name'),
                        'options' => ['placeholder' => 'Выберите руководителя...'],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]); ?>
                </div>
                <!-- <div class="col-md-3 vcenter">
                    <?php /* $form->field($refe, 'object_id')->label()->widget(\kartik\select2\Select2::classname(), [
                        'data' => \yii\helpers\ArrayHelper::map(\app\models\Object::find()->all(), 'id', 'title'),
                        'options' => ['placeholder' => 'Выберите Объект...', 'multiple' => true,
                            'value' => $selected,],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]); */?>
                </div> -->
                <div class="col-md-3 vcenter">
                    <?= $form->field($model, 'command')->label()->widget(\kartik\select2\Select2::classname(), [
                        'data' => \yii\helpers\ArrayHelper::map($users, 'login', 'name'),
                        'options' => ['placeholder' => 'Выберите состав группы проекта...', 'multiple' => true,],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]); ?>
                </div>
            </div>
            <div style="display:none">
            </div>
            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['name' => 'button1','class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                <?= Html::submitButton($model->isNewRecord ? 'Выбрать файл ВР ' : 'Изменить', ['name' => 'button2','class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                <?=$model->id ?Html::a('Добавить отчёт', ['/report/create?project_id='.$model->id],['class'=>'btn btn-success']):''?>
                
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>


    <?php
    $searchModel = new \app\models\ProjectobjectSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $dataProvider->query->andWhere(['project_id' => $model->id]);
    ?>
    <div class="box box-default">
        <div class="box-body" style="overflow-x: auto;">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['label' => 'Объект',
                        'format' => 'raw',
                        'value' => function ($data) {
                            return \app\models\Object::findOne($data->object_id)->title;
                        }],
                    ['label' => 'Добавить работу',
                        'format' => 'raw',
                        'value' => function ($data) {
                            return Html::a('Добавить работу', ['/workcount/create?object_id=' . $data->object_id . '&project_id=' . $data->project_id],['target'=>'_blank']);
                        }],
                ],
            ]); ?>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-12">
        <!— USERS LIST —>
        <div class="box box-danger collapsed-box">
            <div class="box-header with-border">
                <h3 class="box-title">Работы</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                    </button>
                </div>
            </div>
            <!— /.box-header —>
            <div class="box-body no-padding" style="display: none;">
                <?php
                $searchModel = new \app\models\WorkCountSearch();
                $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
                $dataProvider->query->andWhere(['project_id' => $model->id]);
                ?>
                <?php \yii\widgets\Pjax::begin([
                    'enablePushState'=>FALSE
                ]); ?>
                        <?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'id'=>'grid-1',
                            'rowOptions' => function($data){
                                if($data->count_fact >= $data->count){
                                    return ['class' => 'success'];
                                }
                            },
                            'columns' => [
                                ['label' => 'Объект',
                                    'format' => 'raw',
                                    'value' => function ($data) {
                                        $object = \app\models\Object::findOne($data->object_id);
                                        if (!empty($object))
                                        {
                                            return $object->title;
                                        }
                                        return 'Объект удалён';
                                    }],
                                ['label' => 'Раздел',
                                    'format' => 'raw',
                                    'value' => function ($data) {
                                        $object = \app\models\Section::findOne($data->section);
                                        if (!empty($object))
                                        {
                                            return $object->title;
                                        }
                                        return 'Раздел удалён';
                                    }],
                                ['label' => 'Работа',
                                    'format' => 'raw',
                                    'value' => function ($data) {
                                        return \app\models\Work::findOne($data->work_id)->title;
                                    }],
                                ['label' => 'Ед. Изм.',
                                    'format' => 'raw',
                                    'value' => function ($data) {
                                        return \app\models\Work::findOne($data->work_id)->unit;
                                    }],
                                ['label' => 'Количество',
                                    'format' => 'raw',
                                    'value' => function ($data) {
                                        return $data->count;
                                    }],
                                [
                                    'label' => 'Выполнено',
                                    'format' => 'raw',
                                    'value' => function ($data) {
                                        return $data->count_fact;
                                    },
                                ],
                                [
                                    'label' =>'Action',
                                    'value' => function ($model)
                                    {
                                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['/workcount/delete', 'id' => $model->id], ['data' => ['confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),'method' => 'post',],]);
                                    },
                                    'format'=>'raw',
                                ],
                            ],
                        ]); ?>

                <?php \yii\widgets\Pjax::end(); ?>

            </div>
            <div class="box-footer text-center" style="display: none;">

            </div>
        </div>
        <!--/.box —>
      </div>
</div>

views/project/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProjectSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="project-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'pm') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/project/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $refe app\models\ProjectObject */

$refe = new \app\models\ProjectObject();
$this->title = 'Добавить ';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-create">


    <?= $this->render('_form', [
        'refe'=>    $refe,
        'model' => $model,
    ]) ?>

</div>

views/project/excel_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $form yii\widgets\ActiveForm */

$works = new \app\models\ObjectSection();

$alreadySelected = \app\models\ProjectObject::findAll(['project_id' => $model->id]);
$selected = [];
$users = \app\models\Users::find()->all();
foreach ($alreadySelected as $items)
{
    $selected[] = $items->object->id;
}

$data = \app\models\Object::find()->all();
$result = [];
foreach ($data as $item)
{
    $result[$item->id] = $item->title;
}

\yii\helpers\Url::remember();
?>

<div class="project-form">
    <div class="box box-default">
        <div class="box-body">
            <?php $form = ActiveForm::begin(); ?>

            <div class="row">
                <div class="col-md-3 vcenter">
                    <?= $form->field($model, 'title')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>
                </div>
                <div class="col-md-3 vcenter">
                    <?= $form->field($model, 'pm')->widget(\kartik\select2\Select2::classname(), [
                        'data' => \yii\helpers\ArrayHelper::map($users, 'id', 'name'),
                        'disabled' => 'disabled',
                        'options' => ['placeholder' => 'Выберите руководителя...'],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]); ?>
                </div>
                <!-- <div class="col-md-3 vcenter">
                    <?php  /*$form->field($refe, 'object_id')->label()->widget(\kartik\select2\Select2::classname(), [
                        'data' => \yii\helpers\ArrayHelper::map(\app\models\Object::find()->all(), 'id', 'title'),
                        'disabled' => 'disabled',
                        'options' => ['placeholder' => 'Выберите Объект...', 'multiple' => true,
                            'value' => $selected,],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]);*/ ?>
                </div> -->
                <div class="col-md-3 vcenter">
                    <?= $form->field($model, 'command')->label()->widget(\kartik\select2\Select2::classname(), [
                        'data' => \yii\helpers\ArrayHelper::map($users, 'login', 'name'),
                        'disabled' => 'disabled',   
                        'options' => ['placeholder' => 'Выберите состав группы проекта...', 'multiple' => true,],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ]); ?>
                </div>
            </div>
            <div style="display:none">
            </div>
            <div class="form-group">
                <?php //$model->id ?Html::a('Проверить файл', ['/project/getexcel', 'id' => $model->id, 'testing' => '1'],['class'=>'btn btn-success']):''?>
                <?=$model->id ?Html::a($excel_data != null ? 'Добавить ВР в проект' : 'Назад', ['/project/getexcel', 'id' =>$model->id, 'testing' => '2'],['class'=>'btn btn-success']):''?>
                <?=$retry == 1 ?Html::a('Загрузить новый файл ВР', ['/project/upload', 'id' =>$model->id],['class'=>'btn btn-success']):''?>              
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>


    <div class="box box-default">
        <div class="box-body" style="overflow-x: auto;">
            <?php if($excel_data != null) { ?>
                <table class="table table-bordered table-condensed">
                    <tr>
                        <th style="font-size: 15px;" >Проект</th>
                        <th style="font-size: 15px;" >Объект</th>  
                        <th style="font-size: 15px;" >Раздел ПД</th>
                        <th style="font-size: 15px;" >Наименование работы</th> 
                        <th style="font-size: 15px;" >Ед. измерения</th>
                        <th style="font-size: 15px;" >Кол-во</th>                              
                    </tr> 
                <?php
                  foreach ($excel_data as $value) {
                      echo '<tr>'; 
                      foreach ($value as $key) {
                         echo "<td width = 20px >".$key."</td>";
                      }
                      echo "</tr>";
                    }  
                  ?>
                  </table>
            <?php } 
            else { echo '<h2 style=" color:red;"><center>Выбранном excel файле нет новых записей</center</h2>'; }
            ?>
        </div>
    </div>
</div>

views/project/form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Uploads */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="uploads-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'File')->fileInput() ?>

    <div style="display:none;">
    	<?= $form->field($model, 'proyekt_id')->textInput(['maxlength' => true]) ?>
	</div>    

    <div class="form-group">
    <?= Html::submitButton($model->isNewRecord ? 'Импорт' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/project/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Проекты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="project-index">
    <div class="box box-default">
        <div class="box-body">
            <!-- <img src="http://cbscao.ru/sites/default/files/pictures/13249/develop900.jpg" alt="Наш логотип">-->
            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <p>
                <?= Html::a('Добавить', ['create'], ['class' => 'btn btn-success']) ?>
            </p>

        </div>
    </div>
</div>

<div class="box box-default">
    <div class="box-body" style="overflow-x: auto;">
        <?= GridView::widget([
            'responsiveWrap' => false,
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                //['class' => 'yii\grid\SerialColumn'],
                [
                    'attribute' => 'id',
                    'content' => function ($data) {
                        return '<span class="label label-warning" style="font-size:13px;">' . Html::a($data->id . '   ', ['update', 'id' => $data->id], ['style' => 'color:#ffffff;']) . '</span>';

                    },
                ],

                // 'id',
                'title',
                [
                    'attribute' => 'pm',
                    'format' => 'raw',
                    'value' => function ($data) {
                        $user = \app\models\Users::findOne($data->pm);
                        return !empty($user) ? Html::a($user->name , ['users/view', 'id' => $data->pm]): 'Пользователь удалён';
                    }
                ],
                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{delete} {view}'],
                // ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
</div>
</div>

views/project/read_excel.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $refe app\models\ProjectObject */

$refe = new \app\models\ProjectObject();

$this->title = 'Изменить ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="project-update">


    <?= $this->render('excel_form', [
        'model' => $model,
        'refe'=>$refe,
        'excel_data' => $excel_data,
        'retry' => $retry,
    ]) ?>

</div>

views/project/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Project */
/* @var $refe app\models\ProjectObject */

$refe = new \app\models\ProjectObject();

$this->title = 'Изменить ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="project-update">


    <?= $this->render('update_form', [
        'model' => $model,
        'refe'=>$refe,
    ]) ?>

</div>