models/Report.php
<?php

namespace app\models;

use Codeception\Util\Debug;
use Yii;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\UploadedFile;

/**
 * This is the model class for table "report".
 *
 * @property integer $id
 * @property string $done
 * @property integer $project_id
 * @property integer $object_id
 * @property string $future_plan
 * @property string $problems
 * @property string $email_dispatch
 *  Адреса электронныйх почт, на которая произведется рассылка отчета
 * @property integer $creator_id
 * @property string $creation_date
 * @property integer $post_send
 * @property integer $prev_report
 * @property array $user_list
 * @property array $imageFile[]
 * @property array $work
 * @property Project $project
 * @property Users $creator
 *
 * @property Object $object //объект по которому сделан отчет
 *
 */
class Report extends \yii\db\ActiveRecord
{
    public function __construct(array $config = [])
    {
        $this->isSentFlag = false;
        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'report';
    }

    /**
     * @var UploadedFile[]
     */
    public $imageFiles;

    public $has_works;

    public $is_send_report;

    public $isSentFlag; // Флаг сигнализирующий о том, что отчет был отправлен

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['done', 'project_id', 'user_list', 'object_id', 'begin_work'], 'required'],
            [['done', 'future_plan', 'problems', 'has_works'], 'string'],
            ['email_dispatch', 'validateMultiEmails'],
            [['begin_work'], 'default', 'value' => null],
            [['driving', 'renta_avto', 'avto'], 'integer'],
            [['driving', 'renta_avto', 'avto'], 'validateStackAvtoFields'],
            [['project_id', 'creator_id', 'post_send', 'prev_report'], 'integer'],
            [['creation_date', 'imageFiles', 'has_works'], 'safe'],
            [['project_id'], 'exist', 'skipOnError' => true, 'targetClass' => Project::className(), 'targetAttribute' => ['project_id' => 'id']],
            [['creator_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['creator_id' => 'id']],
        ];
    }

    public function validateMultiEmails($attribute, $params, $validator)
    {
        $emails = $this->prepareEmails();

        foreach ($emails as $email) {

            $emailValidator = new \yii\validators\EmailValidator();
            if ($emailValidator->validate($email)) {
                continue;
            } else {
                $this->addError($attribute, 'Присутствуют некорректные адреса электронной почты');
            }
        }
    }

    public function validateStackAvtoFields($attribute, $params, $validator)
    {
        $labels = $this->attributeLabels();
        if (!$this->driving || !$this->renta_avto) {
            if ($this->avto == "") {
                $fields = "Поля ";
                $fields .= $labels['driving'] . " или ";
                $fields .= $labels['renta_avto'] . " и ";
                $fields .= $labels['avto'] . " ";
                $this->addError($attribute, $fields . ' должны быть заполнены совместно');
                $this->addError('avto', $fields . ' должны быть заполнены совместно');
            }

        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID Отчёта',
            'done' => 'Что сделано',
            'work' => 'Работы',
            'project_id' => 'Проект',
            'object_id' => 'Объект',
            'future_plan' => 'План на следующий день',
            'email_dispatch' => 'Список рассылки',
            'problems' => 'Проблемы',
            'creator_id' => 'Создатель',
            'creation_date' => 'Дата создания',
            'post_send' => 'Список получивших',
            'prev_report' => 'Предыдущий отчёт',
            'user_list' => 'Бригада',
            'imageFiles' => 'Приложения к отчету',
            'driving' => 'Водительские (км)',
            'renta_avto' => 'Аренда авто (км)',
            'avto' => 'Автомобиль',
            'begin_work' => 'Дата проведения работ',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProject()
    {
        return $this->hasOne(Project::className(), ['id' => 'project_id']);
    }

    /**
     * Возвращает объект по которому сделан отчет
     * @return \yii\db\ActiveQuery
     */
    public function getObject()
    {
        return $this->hasOne(Object::className(), ['id' => 'object_id']);
    }

    public function getWorks()
    {
        return WorkProcess::find()->where(['report_id' => $this->id])->all();

    }


    public function getAvtomobile()
    {
        return $this->hasOne(Cars::className(), ['id' => 'avto']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreator()
    {
        return $this->hasOne(Users::className(), ['id' => 'creator_id']);
    }


    public function beforeSave($insert)
    {
        if ($this->has_works == null)
            $this->has_works = 0;

        $this->user_list = $_POST['Report']['user_list'];

        $this->user_list = implode(', ', $this->user_list);

        if ($insert) {
            $this->creator_id = Yii::$app->user->id;
        }


        if ($this->isNewRecord) {
            $users = [];

            $data = \app\models\Users::find()->where([
                'in',
                'login',
                \app\models\Project::find($this->project_id)->one()->command
            ])->all();

            foreach ($data as $user) {
                $users[] = $user->email;
            }

            $this->email_dispatch = implode(',', $users);

        }

        if ($this->email_dispatch && !$this->isNewRecord) {
            $this->email_dispatch = implode(',', $this->email_dispatch);
        }

        if ($this->convertFormat()) {
            $this->begin_work = $this->convertFormat();
        }
        if ($this->isNewRecord) {
            $this->creation_date = date('Y-m-d H:i:s');
        }

        return parent::beforeSave($insert);
    }

    public function beforeDelete()
    {
        $workProcesses = WorkProcess::find()->where(['report_id' => $this])->all();
        $photos = Photos::find()->where(['report_id' => $this->id])->all();

        foreach ($workProcesses as $process) {
            $process->delete();
        }

        foreach ($photos as $photo) {
            $photo->delete();
        }

        return parent::beforeDelete();
    }

    public function afterFind()
    {
        parent::afterFind();
        $this->user_list = explode(', ', $this->user_list);
        $this->email_dispatch = explode(', ', $this->email_dispatch);
    }

    public function afterSave($insert, $changedAttributes)
    {
        $isSending = isset($_POST['Report']['is_send_report']) ? $_POST['Report']['is_send_report'] : null;
        if ($this->imageFiles != null) {
            $images = explode(',', $this->imageFiles);
            foreach ($images as $image) {
//                $photo = new Photos(['report_id' => $this->id, 'photo' => $image]);
//                $photo->save();

                //находим фотки в базе и прикрепляем к ним идентификатор отчета
                Photos::updateReportIdByPath($this->id, $image);
            }
        }
        if ($isSending == 1) {

            $userLogins = explode(', ', $this->user_list);

            $userId = Yii::$app->user->getId();
            $sendingUser = Users::findOne(['id' => $userId]);


            $users = Users::find()->where(['in', 'login', $userLogins])->all();

            $usersEmails = ArrayHelper::map($users, 'email', 'name');

            $emails = [];

            if ($this->email_dispatch != null) {
                $emailDispatchesEmails = Users::find()->where(['in', 'email', explode(',',$this->email_dispatch)])->all();
                $emails = ArrayHelper::map($emailDispatchesEmails, 'email', 'name');

            }

            $rejectedEmails = $this->getRejectedEmails();


            $dispatchEmails = array_merge($usersEmails, $emails);

            $project = $this->project;

            if ($project != null) {
                $command = Users::findAll(['login' => $project->command]);
                $commandEmails = ArrayHelper::map($command, 'email', 'name');
                $projectManager = Users::findOne($project->pm);

                if ($projectManager != null) {
                    $dispatchEmails = array_merge($dispatchEmails, [$projectManager->email => $projectManager->name]);
                }
                $dispatchEmails = array_merge($dispatchEmails, $commandEmails);
            }
            

            $dispatchEmails = array_diff($dispatchEmails, $rejectedEmails);

            $dispatchEmails = array_unique($dispatchEmails);

            $messages = [];

            $object = Object::findOne($this->object_id);
            $objectTitle = $object != null ? $object->title : 'Объект удален';

            $project = Object::findOne($this->project_id);
            $projectTitle = $project != null ? $project->title : 'Проект удален';

            $users = Users::findAll($this->user_list);
            $usersList = implode(', ', array_column($users, 'name'));

            foreach ($dispatchEmails as $email) {
                $reportQueue = $this->getReportQueue();
                $html = '';
                foreach ($reportQueue as $report) {
                    $html .= $report->generateReportEmailHtmlBody() . '<hr>';
                }

                //прикрепляем предыдущие отчеты за 7 дней в убывающем порядке
                $html .= $this->getPreviousReports($this->id, $this->begin_work);

                $Cc = [];

                foreach ($dispatchEmails as $ccEmail => $name) {
                    if ($ccEmail != $email) {

views/report/_add_work.php
<?php

/* @var $model app\models\Report */
/* @var $works app\models\Work[] */
/* @var $objects app\models\Object[] */
/* @var $sections app\models\Section[] */
/* @var $newWork app\models\Workcount */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

$getWorkInfoUrl = 'https://'.$_SERVER['SERVER_NAME'].Url::toRoute(['report/get-amounts']);

$jsOnSelect = "function() {
    var project = $('#work-btn_submit').attr('data-project');
    var object = $('#work-btn_submit').attr('data-object');
    var section = $('#work-section-id').val();
    var work = $(this).val();
   
   $.get('{$getWorkInfoUrl}'+'?project='+project+'&object='+object+'&section='+section+'&work='+work, function(data){
        $('#fw_total').val(data.count);
        $('#fw_unit').val(data.units);
        $('#fw_done').val(data.count_fact);
   });
    
    
}";


$filteredSections = [];

foreach($sections as $section)
{
    if($section->object_id == $model->object_id)
    {
        array_push($filteredSections, $section);
    }
}

\app\assets\ReportCreateAsset::register($this);

?>
<?php $workForm = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'action' => Url::toRoute(['report/add_work', 'project_id' => $model->project_id, 'object_id'  => $model->object_id])]]); ?>


        <div class="col-md-2 work-padding">
            <?= $workForm->field($newWork, 'section')->widget(Select2::classname(), [
                'data' => ArrayHelper::map($filteredSections, 'id', 'title'),
                'options' => ['id' => 'work-section-id', 'placeholder' => 'Выберите'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
//                'pluginEvents' => [
//                    "depdrop:afterChange"=>"function(event, id, value) {
//                        var section = value;
//                        alert(section+' '+work);
//                    }",
//                ],
            ]) ?>
        </div>

        <div class="col-md-2 work-padding">
            <?= $workForm->field($newWork, 'work_id')->widget(\kartik\depdrop\DepDrop::classname(), [
                'type' => \kartik\depdrop\DepDrop::TYPE_SELECT2,
                'options' => ['id' => 'work-work-id'],
                'pluginOptions' => [
                    'depends' => ['project', 'object', 'work-section-id'],
                    'placeholder' => 'Выберите раздел...',
                    'url' => \yii\helpers\Url::to(['/report/get-section-works']),
                    'loadingText' => 'Поиск работ'
                ],
//                'pluginEvents' => [
//                    "depdrop:afterChange"=>"function(event, id, value) {
//                        var work = value;
//                        alert(section+' '+work);
//                    }",
//                ],
                'select2Options' => [
                    'pluginEvents' => [
                        "select2:select" => $jsOnSelect,
                    ],
                ],
            ]); ?>
        </div>

        <div class="col-md-1 work-padding">
            <label for="">Всего по ВР</label>
            <input id="fw_total" class="form-control" type="text" name="" readonly>
        </div>
        <div class="col-md-1 work-padding">
            <label for="">Ед. изм.</label>
            <input id="fw_unit" class="form-control" type="text" name="" readonly>
        </div>
        <div class="col-md-2 work-padding">
            <label for="">Сделано ранее</label>
            <input id="fw_done" class="form-control" type="text" name="" readonly>
        </div>
        <div class="col-md-2 work-padding">
            <?= $workForm->field($newWork, 'count')->label('Сделано сегодня')->textInput() ?>
        </div>

        <div class="col-md-2 work-padding">
            <?= Html::a('<i class="fa fa-plus"></i> Добавить работу', '#', ['class' => 'btn btn-success', 'data-project' => $model->project_id, 'data-object' => $model->object_id, 'data-url_getinfo' => $getWorkInfoUrl, 'data-report' => Yii::$app->request->get('id'),'data-url' => 'https://'.$_SERVER['SERVER_NAME'].Url::toRoute(['report/add-work']), 'id' => 'work-btn_submit', 'style' => 'margin-top: 24px']); ?>
        </div>



<?php ActiveForm::end(); ?>
</form>

views/report/_column.php
<?php
use kartik\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

$columnsGrid = [
    //['class' => 'yii\grid\SerialColumn'],

    [
        'encodeLabel' => false,
        'label' => $thFilter,
        'attribute' => 'copy',
        'content' => function ($data) {
            return Html::a('<i class="fa fa-copy"></i>', ['report/create', 'original_id' => $data->id],[
                'class' => 'btn btn-sm btn-default','title' => 'Скопировать отчет'
            ]);

        },
        'width' => '10px',
    ],

    [
        'attribute' => 'id',
        'content' => function ($data) {
            return '<span class="label label-warning" style="font-size:13px;">' . Html::a($data->id . '   ', ['update', 'id' => $data->id], ['style' => 'color:#ffffff;']) . '</span>';

        },
        'width' => '10px',
    ],
    [
        'label' => 'Дата работ',
        'filterType' => GridView::FILTER_DATE_RANGE,
        'filterWidgetOptions' => ([
            'attribute' => 'begin_work',
            'convertFormat' => true,
            'pluginOptions' => [
                'format' => 'Y-m-d',
                'opens' => 'right',

                'locale' => [
                    'cancelLabel' => 'Clear',
                    'format' => 'Y-m-d',],
            ],
        ]),
        'attribute' => 'begin_work',
        'content' => function ($model) {
            if ($model->begin_work) {
                return \DateTime::createFromFormat('Y-m-d H:i:s', $model->begin_work)->format('d.m.Y');
            } else {
                return false;
            }

        },
        'width' => '130px',
    ],
    [
        'content' => function ($model) {
            return '<a class="modal-show" onClick="return show_in_modal(\''.Url::toRoute(['report/view-in-modal', 'id' => $model->id]).'\');" href="' . Url::toRoute(['report/view-in-modal', 'id' => $model->id]) . '"><i class="fa fa-eye"></i></a>';
        },
        'width' => '10px',
    ],
    [
        'attribute' => 'project_id',
        'format' => 'raw',
        'value' => function ($data) {
            $user = \app\models\Project::findOne($data->project_id);
            return !empty($user) ? Html::a($user->title, ['project/update', 'id' => $data->project_id]) : ' Проект удалён';
        },
        'width' => '130px',
    ],

    //объект по которому сделан отчет
    [
        'attribute' => 'object_id',
        'format'  => 'html',
        'value' => function ($data) {
            /** @var \app\models\Object  $object */
            $object = $data->object;

            if ( !$object) {
                return "Объект удален";
            }

            return Html::a($object->title, ['object/view' , 'id' => $object->id]);

        }
    ],


    ['label' => 'ФИО',
        'attribute' => 'creator_id',
        'content' => function ($model) use ($usersMap) {
            foreach ($usersMap as $id => $name) {
                if ($model->creator_id == $id)
                    return $name;
            };
        },
    ],

    [
        'label' => 'Состав бригады',
        'attribute' => 'user_list',
        'content' => function ($model) use ($usersMapByLogins) {
            $content = "";
            foreach ($model->user_list as $user) {
                $liText = isset($usersMapByLogins[$user]) ? $usersMapByLogins[$user] : '<span class="text-danger">Пользователь не найден</span>';
                $content .= "<li>" . $liText . "</li>";
            }
            $content = "<ul style='padding-left: 15px;'>" . $content . "</ul>";

            return $content;
        },
    ],
    // 'id',
    [
        'label' => 'Сделано за день',
        'attribute' => 'done',
        'content' => function ($model) {
            if ($model->done != null) {
                return iconv_substr($model->done, 0, 150, "UTF-8") . '...';
            }
        },
    ],
    [
        'attribute' => 'future_plan',
        'content' => function ($model) {
            if ($model->future_plan != null) {
                return iconv_substr($model->future_plan, 0, 150, "UTF-8") . '...';
            }
        },
    ],
    [
        'attribute' => 'problems',
        'content' => function ($model) {
            if ($model->problems) {
                return iconv_substr($model->problems, 0, 150, "UTF-8") . '...';
            }
        },
    ],

    [
        'label' => 'Должность',
        'filter' => \app\models\Position::positionsList(),
        'attribute' => 'position',
        'content' => function ($model) {
            return isset($model->creator->position->title) ? $model->creator->position->title : "";
        },
    ],


    [
        'attribute' => 'creation_date',
        'filterType' => GridView::FILTER_DATE_RANGE,
        'filterWidgetOptions' => ([
            'attribute' => 'creation_date',
            'convertFormat' => true,
            'pluginOptions' => [
                'format' => 'Y-m-d',
                'opens' => 'left',

                'locale' => [
                    'cancelLabel' => 'Clear',
                    'format' => 'Y-m-d',],
            ],
        ]),
        'content' => function ($model) {
            return \DateTime::createFromFormat('Y-m-d H:i:s', $model->creation_date)->format('d.m.Y H:i:s');
        },
    ],
    // 'creator_id',
    // 'creation_date',
    // 'post_send',
    // 'prev_report',
    ['class' => 'yii\grid\ActionColumn',
        'template' => '{delete}'],
    // ['class' => 'yii\grid\ActionColumn'],
];

views/report/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ReportSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="report-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'done') ?>

    <?= $form->field($model, 'project_id') ?>

    <?= $form->field($model, 'future_plan') ?>

    <?= $form->field($model, 'problems') ?>

    <?php // echo $form->field($model, 'creator_id') ?>

    <?php // echo $form->field($model, 'creation_date') ?>

    <?php // echo $form->field($model, 'post_send') ?>

    <?php // echo $form->field($model, 'prev_report') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/report/_view_modal.php
<?php
/**
 * @var \app\models\Report $model
 */
?>
<div class="row">
    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('project_id') ?></h4>
        <p><?= stripslashes(nl2br($model->project->title)) ?></p>
    </div>

    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('object_id') ?></h4>
        <p><?= stripslashes(nl2br($model->object->title)) ?></p>
    </div>

    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('begin_work') ?></h4>
        <p><?= stripslashes(nl2br(\DateTime::createFromFormat('Y-m-d H:i:s', $model->begin_work)->format('d.m.Y'))) ?></p>
    </div>

</div>
<div class="row">
    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('done') ?></h4>
        <p><?= stripslashes(nl2br($model->done)) ?></p>
    </div>

    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('future_plan') ?></h4>
        <p><?= stripslashes(nl2br($model->future_plan)) ?></p>
    </div>

    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('problems') ?></h4>
        <p><?= stripslashes(nl2br($model->problems)) ?></p>
    </div>

</div>

<div class="row">
    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('driving') ?></h4>
        <p><?= stripslashes(nl2br($model->driving)) ?></p>
    </div>

    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('renta_avto') ?></h4>
        <p><?= stripslashes(nl2br($model->renta_avto)) ?></p>
    </div>

    <div class="col-md-4">
        <h4><?= $model->getAttributeLabel('avto') ?></h4>
        <p><?= stripslashes(nl2br(isset($model->avtomobile->name)?$model->avtomobile->name:"")) ?></p>
    </div>

</div>
<?php if ($model->works): ?>
<div class="row">
    <?php foreach ($model->works as $key => $work): ?>
        <?php if (!$key): ?>
            <div class="col-md-3">
                <h4><?= $work->workcount->getAttributeLabel('work_id') ?></h4>

            </div>

            <div class="col-md-3">
                <h4><?= $work->workcount->getAttributeLabel('count') ?></h4>

            </div>

            <div class="col-md-3">
                <h4><?= $work->workcount->getAttributeLabel('count_fact') ?></h4>

            </div>
            <div class="col-md-3">
                <h4><?= $work->getAttributeLabel('count_daily') ?></h4>

            </div>
        <?php endif; ?>
        <div class="col-md-3">

            <p><?= stripslashes(nl2br($work->workcount->work->title)) ?></p>
        </div>

        <div class="col-md-3">

            <p><?= stripslashes(nl2br($work->workcount->count)) ?></p>
        </div>

        <div class="col-md-3">

            <p><?= stripslashes(nl2br($work->workcount->count_fact)) ?></p>
        </div>
        <div class="col-md-3">

            <p><?= stripslashes(nl2br($work->count_daily)) ?></p>
        </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

views/report/_work_table.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use kartik\grid\GridView;

if(Yii::$app->requestedAction->id == 'update')
{
    $report_id = Yii::$app->request->get('id');
}

?>

<?= GridView::widget([
    'dataProvider' => $processesDataProvider,
    'responsiveWrap' => false,
    'tableOptions' => ['border' => 1],
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        [
            'label' => 'Объект',
            'content' => function($data) use ($workcounts, $objects){
                foreach ($workcounts as $workcount)
                {
                    if($data->workcount_id == $workcount->id)
                    {
                        foreach ($objects as $object)
                        {
                            if($workcount->object_id == $object->id)
                                return $object->title;
                        }
                    }
                }
            }
        ],
        [
            'label' => 'Раздел',
            'content' => function($data) use ($workcounts, $sections){
                foreach ($workcounts as $workcount)
                {
                    if($data->workcount_id == $workcount->id)
                    {
                        foreach ($sections as $section)
                        {
                            if($workcount->section == $section->id)
                                return $section->title;
                        }
                    }
                }
            }
        ],
        [
            'label' => 'Работа',
            'content' => function($data) use ($workcounts, $works){
                foreach ($workcounts as $workcount)
                {
                    if($data->workcount_id == $workcount->id)
                    {
                        foreach ($works as $work)
                        {
                            if($workcount->work_id == $work->id)
                                return $work->title;
                        }
                    }
                }
            }
        ],
        [
            'label' => 'Всего по проекту',
            'content' => function($data) use ($workcounts){
                foreach ($workcounts as $workcount)
                {
                    if($data->workcount_id == $workcount->id)
                    {
                        return $workcount->count;
                    }
                }
            }
        ],
        [
            'label' => 'Ед.изм.',
            'content' => function($data) {
                return $data->workcount->units;
            }
        ],
        [
            'label' => 'Сделано ранее',
            'content' => function($data) use ($workcounts){
                foreach ($workcounts as $workcount)
                {
                    if($data->workcount_id == $workcount->id)
                    {
                        return $workcount->count_fact;
                    }
                }
            }
        ],
        'count_daily',
        [
            'attribute' => 'date',
            'content' => function ($data) {
                if ($data->date) {
                    return \DateTime::createFromFormat('Y-m-d H:i:s', $data->date)->format('d.m.Y H:i:s');
                } else {
                    return false;
                }

            },
        ],

         ['class' => 'yii\grid\ActionColumn',
             'template' => '{delete}',
             'buttons' => [
                 'delete' => function($url, $model) use ($report_id){
                     $url = Url::to(['report/delete-process', 'id' => $model->id, 'report_id' => $report_id]);
                     return Html::a('<i class="fa fa-trash text-danger" style="font-size: 18px;"></i>', $url, ['title' => 'Удалить']);
                 },
             ],
             'visible' => $report_id != null ? true : false,
         ],
    ],
]); ?>

views/report/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Report */
/* @var $works app\models\Work[] */
/* @var $objects app\models\Object[] */
/* @var $sections app\models\Section[] */
/* @var $newWork app\models\Workcount */

$this->title = 'Добавить ';
$this->params['breadcrumbs'][] = ['label' => 'Отчеты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="report-create">


    <?= $this->render('_form', [
        'model' => $model,
        'works' => $works,
        'sections' => $sections,
        'newWork' => $newWork,
        'workcounts' => $workcounts,
        'objects' => $objects,
        'processesDataProvider' => $processesDataProvider,
    ]) ?>

</div>

views/report/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Report */
/* @var $works app\models\Work[] */
/* @var $objects app\models\Object[] */
/* @var $sections app\models\Section[] */
/* @var $photos app\models\Photos[] */
/* @var $newWork app\models\Workcount */

$this->title = 'Изменить ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Отчеты', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['update', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="report-update">


    <?= $this->render('_form', [
        'model' => $model,
        'works' => $works,
        'sections' => $sections,
        'newWork' => $newWork,
        'workcounts' => $workcounts,
        'objects' => $objects,
        'photos' => $photos,
        'processesDataProvider' => $processesDataProvider,
    ]) ?>

</div>